# Generated by Django 6.1.1 on 2026-09-18 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('portada_url', models.URLField(blank=True, null=True)),
                ('generos', models.CharField(blank=True, max_length=255)),
                ('plataformas', models.CharField(blank=True, max_length=255)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('metacritic', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JuegoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('jugando', 'Jugando'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='pendiente', max_length=20)),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horas_jugadas', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('resena', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'juego')},
            },
        ),
    ]
